In [ ]:
!pip install datasets
!pip install transformers

Collecting datasets
  Downloading datasets-3.5.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.12.0,>=2023.1.0 (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.14)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.29.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.2.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.13.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.5.0-py3-none-any.whl (491 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.2/491.2 kB 22.3 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 9.9 MB/s eta 0:00:00
Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 12.8 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 12.4 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 14.4 MB/s eta 0:00:00
Installing collected packages: xxhash, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.6.0+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.6.0+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.12.0 which is incompatible.
Successfully installed datasets-3.5.0 dill-0.3.8 fsspec-2024.12.0 multiprocess-0.70.16 xxhash-3.5.0
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.50.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.29.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (2024.12.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (4.13.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)

In [ ]:
from datasets import Dataset
from sklearn.model_selection import KFold
import numpy as np
import pandas as pd
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import Trainer, TrainingArguments
import torch
from sklearn.metrics import accuracy_score, f1_score

# 1. Load data
df = pd.read_csv('abstract.csv').head(20)  # Using first 20 rows
dataset = Dataset.from_pandas(df)

# 2. SciBERT setup
model_name = "allenai/scibert_scivocab_uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

# 3. Correct Tokenization function (with proper label handling)
def tokenize_function(examples):
    tokenized = tokenizer(examples["text"], padding="max_length", truncation=True, max_length=128)
    # Convert labels to LONG (int64) for classification
    tokenized["label"] = [int(label) for label in examples["label"]]
    return tokenized

# 4. Prepare k-fold splits
texts = dataset["Abstract"]
labels = dataset["label"]
kf = KFold(n_splits=3, shuffle=True, random_state=42)  # Reduced folds for small data

# 5. Evaluation metric
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    return {
        'accuracy': accuracy_score(labels, preds),
        'f1': f1_score(labels, preds, average='weighted')
    }

for fold, (train_idx, val_idx) in enumerate(kf.split(texts)):
    print(f"\n=== Fold {fold + 1} ===")

    # Create splits with INTEGER labels
    train_data = Dataset.from_dict({
        "text": np.array(texts)[train_idx].tolist(),
        "label": np.array(labels)[train_idx].astype(np.int64)  # Critical fix: int64 instead of float
    })
    val_data = Dataset.from_dict({
        "text": np.array(texts)[val_idx].tolist(),
        "label": np.array(labels)[val_idx].astype(np.int64)    # Same fix here
    })

    # Tokenize
    tokenized_train = train_data.map(tokenize_function, batched=True)
    tokenized_val = val_data.map(tokenize_function, batched=True)

    # Initialize model
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=len(np.unique(labels)),
        problem_type="single_label_classification"
    )

    # Training args optimized for small batches
    training_args = TrainingArguments(
        output_dir=f"./scibert_fold_{fold+1}",
        evaluation_strategy="steps",
        eval_steps=2,
        per_device_train_batch_size=4,
        per_device_eval_batch_size=4,
        gradient_accumulation_steps=5,  # Effective batch size = 20
        num_train_epochs=15,
        learning_rate=2e-5,
        save_strategy="no",
        logging_steps=1,
        fp16=torch.cuda.is_available(),
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_train,
        eval_dataset=tokenized_val,
        compute_metrics=compute_metrics,
    )

    print(f"Training samples: {len(train_data)}, Validation samples: {len(val_data)}")
    trainer.train()
    results = trainer.evaluate()
    print(f"Fold {fold+1} Results:", results)

=== Fold 1 ===

Map:   0%|          | 0/13 [00:00<?, ? examples/s]

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at allenai/scibert_scivocab_uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1611: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Training samples: 13, Validation samples: 7

Fold 1 Results: {'eval_loss': 0.0, 'eval_accuracy': 1.0, 'eval_f1': 1.0, 'eval_runtime': 2.7892, 'eval_samples_per_second': 2.51, 'eval_steps_per_second': 0.717, 'epoch': 0}

=== Fold 2 ===

Map:   0%|          | 0/13 [00:00<?, ? examples/s]

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at allenai/scibert_scivocab_uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1611: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Training samples: 13, Validation samples: 7

KeyboardInterrupt:

In [ ]:
from datasets import Dataset
from sklearn.model_selection import KFold
import numpy as np
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import Trainer, TrainingArguments
from sklearn.metrics import accuracy_score, f1_score
from collections import Counter

# 1. Enhanced Data Loading with Validation
df = pd.read_csv('abstract.csv')
head_10 = df.head(10)

# Get 10 from the tail
tail_10 = df.tail(10)

# Concatenate them
combined_df = pd.concat([head_10, tail_10]).reset_index(drop=True)
#Randomly select 20 rows
df = combined_df
print("\n=== Data Integrity Check ===")
print(f"Total samples: {len(df)}")
print("Label distribution:", Counter(df['label']))
print("Null values:\n", df.isnull().sum())

# Data Cleaning
df = df.dropna(subset=['Abstract', 'label'])
df = df[df['Abstract'].str.strip().astype(bool)]

# 2. Label Processing with Verification
print("\nOriginal label values:", sorted(df['label'].unique()))
df['label'] = pd.factorize(df['label'])[0]  # Convert to 0-indexed integers
print("Processed labels:", sorted(df['label'].unique()))

# 3. Dataset Preparation with Train/Test Split
dataset = Dataset.from_pandas(df)
texts = dataset["Abstract"]
labels = dataset["label"]

# 4. Debugging KFold Implementation
kf = KFold(n_splits=2, shuffle=True, random_state=42)
for fold, (train_idx, val_idx) in enumerate(kf.split(texts, labels)):
    print(f"\n=== Fold {fold+1} === [Train: {len(train_idx)}, Val: {len(val_idx)}]")

    # Verify no overlap
    assert len(set(train_idx) & set(val_idx)) == 0, "Data leakage detected!"

    # Sample inspection
    print("Sample train labels:", [labels[i] for i in train_idx[:5]])
    print("Sample val labels:", [labels[i] for i in val_idx[:5]])

# 5. Model Setup with Debugging
model_name = "allenai/scibert_scivocab_uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    return tokenizer(examples["Abstract"], padding="max_length", truncation=True, max_length=128)

# 6. Modified Training Loop with Early Stopping
for fold, (train_idx, val_idx) in enumerate(kf.split(texts, labels)):
    print(f"\n\n===== Fold {fold+1} =====")

    # Create datasets
    train_data = Dataset.from_dict({"Abstract": [texts[i] for i in train_idx],
                                     "label": [labels[i] for i in train_idx]})
    val_data = Dataset.from_dict({"Abstract": [texts[i] for i in val_idx],
                                   "label": [labels[i] for i in val_idx]})

    # Tokenize with verification
    tokenized_train = train_data.map(tokenize_function, batched=True)
    tokenized_val = val_data.map(tokenize_function, batched=True)

    print("\nFirst training sample:", tokenized_train[0])
    print("First validation sample:", tokenized_val[0])

    # Model initialization with config
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=len(np.unique(labels)),
        problem_type="single_label_classification"
    )

    # Conservative training parameters
    training_args = TrainingArguments(
        output_dir=f"./fold_{fold+1}",
        per_device_train_batch_size=4,
        per_device_eval_batch_size=4,
        num_train_epochs=5,
        evaluation_strategy="steps",
        eval_steps=10,
        logging_steps=5,
        learning_rate=2e-5,
        weight_decay=0.01,
        load_best_model_at_end=False,
        metric_for_best_model='f1',
        greater_is_better=True,
        fp16=torch.cuda.is_available(),
        report_to="none"
    )

    # Custom compute_metrics with debugging
    def compute_metrics(p):
        preds = p.predictions.argmax(-1)
        print("\nPrediction samples:", list(zip(p.label_ids[:5], preds[:5])))
        print("Unique Predictions:", np.unique(preds))
        return {
            'accuracy': accuracy_score(p.label_ids, preds),
            'f1': f1_score(p.label_ids, preds, average='weighted')
        }

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_train,
        eval_dataset=tokenized_val,
        compute_metrics=compute_metrics,
    )

    # Training with progress monitoring
    print("\nStarting training...")
    trainer.train()

    predictions = trainer.predict(tokenized_val)
    print("Unique predictions from the validation set:", np.unique(predictions.predictions.argmax(-1)))

    # Detailed evaluation
    print("\nFinal evaluation:")
    results = trainer.evaluate()
    print({k: v for k, v in results.items() if k in ['eval_accuracy', 'eval_f1', 'eval_loss']})

    # Prediction analysis
    print("\nMisclassified examples:")
    preds = predictions.predictions.argmax(-1)
    for i in range(min(10, len(val_idx))):
        if preds[i] != labels[val_idx[i]]:
            print(f"\nText: {texts[val_idx[i]][:100]}...")
            print(f"True: {labels[val_idx[i]]}, Predicted: {preds[i]}")

=== Data Integrity Check ===
Total samples: 20
Label distribution: Counter({0: 10, 1: 10})
Null values:
 label       0
Abstract    0
dtype: int64

Original label values: [np.int64(0), np.int64(1)]
Processed labels: [np.int64(0), np.int64(1)]

=== Fold 1 === [Train: 10, Val: 10]
Sample train labels: [0, 0, 0, 0, 0]
Sample val labels: [0, 0, 0, 0, 0]

=== Fold 2 === [Train: 10, Val: 10]
Sample train labels: [0, 0, 0, 0, 0]
Sample val labels: [0, 0, 0, 0, 0]


===== Fold 1 =====

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

First training sample: {'Abstract': 'As the complexity of our neural network models grow,  so too do the data and computation requirements for successful training.  One proposed solution to this problem is training on a distributed network of computational devices, thus distributing the computational and data storage loads.  This strategy has already seen some adoption by the likes of Google and other companies.  In this paper we propose a new method of distributed, decentralized learning that allows a network of computation nodes to coordinate their training using asynchronous updates over an unreliable network while only having access to a local dataset.  This is achieved by taking inspiration from Distributed Averaging Consensus algorithms to coordinate the various nodes.  Sharing the internal model instead of the training data allows the original raw data to remain with the computation node.  The asynchronous nature and lack of centralized coordination allows this paradigm to function with limited communication requirements.  We demonstrate our method on the MNIST, Fashion MNIST, and CIFAR10 datasets. We show that our coordination method allows models to be learned on highly biased datasets, and in the presence of intermittent communication failure.', 'label': 0, 'input_ids': [102, 188, 111, 3480, 131, 580, 3687, 934, 1262, 1126, 422, 564, 3872, 572, 111, 453, 137, 3937, 3420, 168, 3026, 2208, 205, 482, 1337, 1368, 147, 238, 1167, 165, 2208, 191, 106, 2798, 934, 131, 3989, 3410, 422, 959, 28046, 111, 3989, 137, 453, 4197, 10012, 205, 238, 2691, 434, 3440, 2187, 693, 9714, 214, 111, 1967, 30113, 131, 13387, 137, 494, 6724, 205, 121, 238, 1203, 185, 4459, 106, 758, 551, 131, 2798, 422, 18892, 1904, 198, 2890, 106, 934, 131, 3937, 2207, 147, 6858, 547, 2208, 487, 14504, 11370, 573, 130, 22923, 934, 969, 617, 2773, 1899, 147, 106, 1338, 4813, 205, 238, 165, 3178, 214, 3841, 26273, 263, 2798, 11558, 6921, 2617, 147, 6858, 111, 1711, 2207, 205, 6404, 111, 2924, 437, 3222, 103], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
First validation sample: {'Abstract': 'We propose a generalized probability kernel on discrete distributions with finite support. This probability kernel, defined as kernel between distributions instead of samples, generalizes a variety of existing discrepancy statistics including maximum mean discrepancy(MMD) as well as kernelized Stein discrepancy(KSD), and extends to more general cases. For both existing and newly proposed statistics, we estimate them through empirical frequency and illustrate the strategy to search for the unbiased ones. We further analyze several unbiased plugin(empirical) estimators for the task of two-sample test. Our work connects the fields of discrete distribution-property estimation and kernel-based hypothesis test, which might shed light on more new possibilities.', 'label': 0, 'input_ids': [102, 185, 4459, 106, 5957, 2064, 6108, 191, 4829, 4620, 190, 3427, 1385, 205, 238, 2064, 6108, 422, 1565, 188, 6108, 467, 4620, 3222, 131, 1488, 422, 16960, 30113, 106, 3835, 131, 3302, 12332, 4530, 1471, 2050, 1108, 12332, 145, 1100, 30118, 546, 188, 804, 188, 6108, 645, 14869, 12332, 145, 9000, 30118, 546, 422, 137, 10615, 147, 475, 1196, 1299, 205, 168, 655, 3302, 137, 7737, 1337, 4530, 422, 185, 2812, 1445, 833, 4808, 1610, 137, 7416, 111, 2691, 147, 2322, 168, 111, 18344, 4523, 205, 185, 911, 5230, 1323, 18344, 12106, 107, 145, 4808, 546, 15390, 168, 111, 2188, 131, 502, 579, 1498, 856, 205, 580, 697, 19825, 111, 3975, 131, 4829, 1382, 579, 3713, 3261, 137, 6108, 579, 791, 3323, 856, 422, 334, 1799, 103], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at allenai/scibert_scivocab_uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1611: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Starting training...

Prediction samples: [(np.int64(0), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(0))]
Unique Predictions: [0 1]

Prediction samples: [(np.int64(0), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(0))]
Unique Predictions: [0 1]
Unique predictions from the validation set: [0 1]

Final evaluation:

Prediction samples: [(np.int64(0), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(0))]
Unique Predictions: [0 1]
{'eval_loss': 0.5449784398078918, 'eval_accuracy': 0.8, 'eval_f1': 0.7916666666666667}

Misclassified examples:

Text: Learning causal relationships in high-dimensional data (images, videos) is a hard task, as they are ...
True: 1, Predicted: 0

Text: Discovering relevant input features for predicting a target variable is a key scientific question. H...
True: 1, Predicted: 0


===== Fold 2 =====

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

First training sample: {'Abstract': 'We propose a generalized probability kernel on discrete distributions with finite support. This probability kernel, defined as kernel between distributions instead of samples, generalizes a variety of existing discrepancy statistics including maximum mean discrepancy(MMD) as well as kernelized Stein discrepancy(KSD), and extends to more general cases. For both existing and newly proposed statistics, we estimate them through empirical frequency and illustrate the strategy to search for the unbiased ones. We further analyze several unbiased plugin(empirical) estimators for the task of two-sample test. Our work connects the fields of discrete distribution-property estimation and kernel-based hypothesis test, which might shed light on more new possibilities.', 'label': 0, 'input_ids': [102, 185, 4459, 106, 5957, 2064, 6108, 191, 4829, 4620, 190, 3427, 1385, 205, 238, 2064, 6108, 422, 1565, 188, 6108, 467, 4620, 3222, 131, 1488, 422, 16960, 30113, 106, 3835, 131, 3302, 12332, 4530, 1471, 2050, 1108, 12332, 145, 1100, 30118, 546, 188, 804, 188, 6108, 645, 14869, 12332, 145, 9000, 30118, 546, 422, 137, 10615, 147, 475, 1196, 1299, 205, 168, 655, 3302, 137, 7737, 1337, 4530, 422, 185, 2812, 1445, 833, 4808, 1610, 137, 7416, 111, 2691, 147, 2322, 168, 111, 18344, 4523, 205, 185, 911, 5230, 1323, 18344, 12106, 107, 145, 4808, 546, 15390, 168, 111, 2188, 131, 502, 579, 1498, 856, 205, 580, 697, 19825, 111, 3975, 131, 4829, 1382, 579, 3713, 3261, 137, 6108, 579, 791, 3323, 856, 422, 334, 1799, 103], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
First validation sample: {'Abstract': 'As the complexity of our neural network models grow,  so too do the data and computation requirements for successful training.  One proposed solution to this problem is training on a distributed network of computational devices, thus distributing the computational and data storage loads.  This strategy has already seen some adoption by the likes of Google and other companies.  In this paper we propose a new method of distributed, decentralized learning that allows a network of computation nodes to coordinate their training using asynchronous updates over an unreliable network while only having access to a local dataset.  This is achieved by taking inspiration from Distributed Averaging Consensus algorithms to coordinate the various nodes.  Sharing the internal model instead of the training data allows the original raw data to remain with the computation node.  The asynchronous nature and lack of centralized coordination allows this paradigm to function with limited communication requirements.  We demonstrate our method on the MNIST, Fashion MNIST, and CIFAR10 datasets. We show that our coordination method allows models to be learned on highly biased datasets, and in the presence of intermittent communication failure.', 'label': 0, 'input_ids': [102, 188, 111, 3480, 131, 580, 3687, 934, 1262, 1126, 422, 564, 3872, 572, 111, 453, 137, 3937, 3420, 168, 3026, 2208, 205, 482, 1337, 1368, 147, 238, 1167, 165, 2208, 191, 106, 2798, 934, 131, 3989, 3410, 422, 959, 28046, 111, 3989, 137, 453, 4197, 10012, 205, 238, 2691, 434, 3440, 2187, 693, 9714, 214, 111, 1967, 30113, 131, 13387, 137, 494, 6724, 205, 121, 238, 1203, 185, 4459, 106, 758, 551, 131, 2798, 422, 18892, 1904, 198, 2890, 106, 934, 131, 3937, 2207, 147, 6858, 547, 2208, 487, 14504, 11370, 573, 130, 22923, 934, 969, 617, 2773, 1899, 147, 106, 1338, 4813, 205, 238, 165, 3178, 214, 3841, 26273, 263, 2798, 11558, 6921, 2617, 147, 6858, 111, 1711, 2207, 205, 6404, 111, 2924, 437, 3222, 103], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at allenai/scibert_scivocab_uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1611: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Starting training...

Prediction samples: [(np.int64(0), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(1))]
Unique Predictions: [1]

Prediction samples: [(np.int64(0), np.int64(0)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(1))]
Unique Predictions: [0 1]
Unique predictions from the validation set: [0 1]

Final evaluation:

Prediction samples: [(np.int64(0), np.int64(0)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(1))]
Unique Predictions: [0 1]
{'eval_loss': 0.6150730848312378, 'eval_accuracy': 0.6, 'eval_f1': 0.5238095238095238}

Misclassified examples:

Text: Embedding logical knowledge information into text generation is a challenging NLP task. In this pape...
True: 0, Predicted: 1

Text: Post-training dropout based approaches achieve high sparsity and are well established means of decip...
True: 0, Predicted: 1

Text: Variational Auto Encoder (VAE) provide an efficient latent space representation of complex data dist...
True: 0, Predicted: 1

Text: We present a new method for searching optimal hyperparameters among several tasks and several criter...
True: 0, Predicted: 1